# Generated by Django 5.2.1 on 2025-06-07 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comodidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Wi-Fi, Ar Condicionado, Piscina, Garagem', max_length=100, unique=True, verbose_name='nome da comodidade')),
            ],
            options={
                'verbose_name': 'Comodidade',
                'verbose_name_plural': 'Comodidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome do prédio/condomínio')),
                ('endereco_completo', models.CharField(max_length=255, verbose_name='endereço completo')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(help_text='Ex: BA, SP, RJ', max_length=2, verbose_name='estado (UF)')),
                ('cep', models.CharField(help_text='Formato: 12345-678', max_length=9, verbose_name='CEP')),
                ('foto_fachada', models.ImageField(blank=True, help_text='Foto da fachada do prédio ou condomínio.', null=True, upload_to='predios/fachadas/%Y/%m/%d/', verbose_name='foto da fachada')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
            ],
            options={
                'verbose_name': 'Prédio / Condomínio',
                'verbose_name_plural': 'Prédios / Condomínios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Apto 101, Bloco A - Apto 204, Casa 3B', max_length=100, verbose_name='identificador da unidade')),
                ('descricao', models.TextField(blank=True, help_text='Descreva detalhes específicos desta unidade, se houver.', verbose_name='descrição da unidade')),
                ('numero_quartos', models.PositiveIntegerField(default=1, verbose_name='número de quartos')),
                ('numero_banheiros', models.PositiveIntegerField(default=1, verbose_name='número de banheiros')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='área (m²)')),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço da diária (R$)')),
                ('foto_principal', models.ImageField(blank=True, help_text='A foto de capa do anúncio desta unidade.', null=True, upload_to='apartamentos/fotos_principais/%Y/%m/%d/', verbose_name='foto principal da unidade')),
                ('disponivel', models.BooleanField(default=True, verbose_name='disponível para aluguel?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meus_apartamentos', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
                ('comodidades', models.ManyToManyField(blank=True, to='apartamentos.comodidade', verbose_name='comodidades da unidade')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='apartamentos.predio', verbose_name='prédio / condomínio')),
            ],
            options={
                'verbose_name': 'Apartamento / Unidade',
                'verbose_name_plural': 'Apartamentos / Unidades',
                'ordering': ['predio', 'titulo'],
                'unique_together': {('predio', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='FotoApartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Envie uma imagem da galeria do apartamento.', upload_to='apartamentos/galeria/%Y/%m/%d/', verbose_name='imagem')),
                ('legenda', models.CharField(blank=True, max_length=150, null=True, verbose_name='legenda da foto')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='data do upload')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='apartamentos.apartamento', verbose_name='apartamento')),
            ],
            options={
                'verbose_name': 'Foto do Apartamento',
                'verbose_name_plural': 'Fotos dos Apartamentos',
                'ordering': ['data_upload'],
            },
        ),
    ]
