# Generated by Django 5.2.3 on 2025-08-25 13:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comodidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nome da comodidade"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comodidade",
                "verbose_name_plural": "Comodidades",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Apartamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=100, verbose_name="identificador da unidade"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="descrição da unidade"),
                ),
                (
                    "numero_quartos",
                    models.PositiveIntegerField(
                        default=1, verbose_name="número de quartos"
                    ),
                ),
                (
                    "numero_banheiros",
                    models.PositiveIntegerField(
                        default=1, verbose_name="número de banheiros"
                    ),
                ),
                (
                    "area_m2",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="área (m²)"
                    ),
                ),
                (
                    "preco_diaria",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="preço da diária (R$)",
                    ),
                ),
                (
                    "preco_mensal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deixe em branco se não oferecer aluguel mensal.",
                        max_digits=10,
                        null=True,
                        verbose_name="preço do mês (R$)",
                    ),
                ),
                (
                    "foto_principal",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="apartamentos/fotos_principais/%Y/%m/%d/",
                        verbose_name="foto principal da unidade",
                    ),
                ),
                (
                    "disponivel",
                    models.BooleanField(
                        default=True, verbose_name="disponível para aluguel?"
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data de atualização"
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meus_apartamentos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="proprietário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartamento / Unidade",
                "verbose_name_plural": "Apartamentos / Unidades",
                "ordering": ["predio", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="ApartamentoComodidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Custo extra por diária para esta comodidade, se houver.",
                        max_digits=10,
                        verbose_name="preço adicional (R$)",
                    ),
                ),
                (
                    "apartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apartamentos.apartamento",
                    ),
                ),
                (
                    "comodidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apartamentos.comodidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comodidade do Apartamento",
                "verbose_name_plural": "Comodidades do Apartamento",
                "unique_together": {("apartamento", "comodidade")},
            },
        ),
        migrations.AddField(
            model_name="apartamento",
            name="comodidades",
            field=models.ManyToManyField(
                blank=True,
                through="apartamentos.ApartamentoComodidade",
                to="apartamentos.comodidade",
                verbose_name="comodidades da unidade",
            ),
        ),
        migrations.CreateModel(
            name="FotoApartamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="apartamentos/fotos/")),
                ("principal", models.BooleanField(default=False)),
                (
                    "apartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="apartamentos.apartamento",
                    ),
                ),
            ],
            options={
                "ordering": ["-principal"],
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("CLIENTE", "Cliente"),
                            ("PROPRIETARIO", "Proprietário"),
                            ("GERENTE", "Gerente"),
                            ("FUNCIONARIO", "Funcionário"),
                        ],
                        default="CLIENTE",
                        max_length=20,
                        verbose_name="cargo",
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="usuarios/fotos_perfil/%Y/%m/%d/",
                        verbose_name="foto de perfil",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="biografia")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
            },
        ),
        migrations.CreateModel(
            name="Predio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, verbose_name="nome do prédio/condomínio"
                    ),
                ),
                (
                    "endereco_completo",
                    models.CharField(max_length=255, verbose_name="endereço completo"),
                ),
                ("cidade", models.CharField(max_length=100, verbose_name="cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="estado (UF)")),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                (
                    "foto_fachada",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="predios/fachadas/%Y/%m/%d/",
                        verbose_name="foto da fachada",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de cadastro"
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="proprietário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prédio / Condomínio",
                "verbose_name_plural": "Prédios / Condomínios",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="apartamento",
            name="predio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartamentos",
                to="apartamentos.predio",
                verbose_name="prédio / condomínio",
            ),
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_checkin", models.DateField(verbose_name="data de check-in")),
                ("data_checkout", models.DateField(verbose_name="data de check-out")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "data_reserva",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data da reserva"
                    ),
                ),
                (
                    "apartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="apartamentos.apartamento",
                    ),
                ),
                (
                    "hospede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-data_reserva"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.IntegerField(
                        help_text="Nota de 1 a 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comentario",
                    models.TextField(
                        blank=True,
                        help_text="Deixe seu comentário sobre a estadia.",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="apartamentos.reserva",
                    ),
                ),
            ],
        ),
    ]
