# Generated by Django 5.2.1 on 2025-06-09 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto que será exibida no seu perfil.', null=True, upload_to='usuarios/fotos_perfil/%Y/%m/%d/', verbose_name='foto de perfil')),
                ('telefone', models.CharField(blank=True, help_text='Telefone para contato, ex: (74) 99999-9999', max_length=20, verbose_name='telefone')),
                ('bio', models.TextField(blank=True, help_text='Fale um pouco sobre você.', verbose_name='biografia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
