# Generated by Django 5.2.3 on 2025-06-15 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartamentos", "0002_perfil"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_checkin", models.DateField(verbose_name="data de check-in")),
                ("data_checkout", models.DateField(verbose_name="data de check-out")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "data_reserva",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data da reserva"
                    ),
                ),
                (
                    "apartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="apartamentos.apartamento",
                        verbose_name="apartamento",
                    ),
                ),
                (
                    "hospede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="hóspede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-data_reserva"],
            },
        ),
    ]
