# Generated by Django 5.2.3 on 2025-06-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartamentos", "0003_reserva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="data_checkin",
            field=models.DateField(verbose_name="data de check-in (ENTRADA)"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="data_checkout",
            field=models.DateField(verbose_name="data de check-out (SAÍDA)"),
        ),
    ]
