# Generated by Django 5.2.3 on 2025-06-18 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartamentos", "0004_alter_reserva_data_checkin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("CLIENTE", "Cliente"),
                    ("PROPRIETARIO", "Proprietário"),
                    ("GERENTE", "Gerente"),
                    ("FUNCIONARIO", "Funcionário"),
                ],
                default="CLIENTE",
                max_length=20,
                verbose_name="cargo",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="bio",
            field=models.TextField(blank=True, verbose_name="biografia"),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="usuarios/fotos_perfil/%Y/%m/%d/",
                verbose_name="foto de perfil",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="telefone"),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="data_checkin",
            field=models.DateField(verbose_name="data de check-in"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="data_checkout",
            field=models.DateField(verbose_name="data de check-out"),
        ),
    ]
