# Generated by Django 5.2.3 on 2025-06-24 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartamentos", "0005_perfil_cargo_alter_perfil_bio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="predio",
            name="proprietario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predios",
                to=settings.AUTH_USER_MODEL,
                verbose_name="proprietário",
            ),
            preserve_default=False,
        ),
    ]
