# Generated by Django 5.2.3 on 2025-06-25 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartamentos", "0006_predio_proprietario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fotoapartamento",
            options={
                "verbose_name": "Foto do Apartamento",
                "verbose_name_plural": "Fotos dos Apartamentos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="apartamento",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="fotoapartamento",
            name="data_upload",
        ),
        migrations.AlterField(
            model_name="apartamento",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="descrição da unidade"),
        ),
        migrations.AlterField(
            model_name="apartamento",
            name="foto_principal",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="apartamentos/fotos_principais/%Y/%m/%d/",
                verbose_name="foto principal da unidade",
            ),
        ),
        migrations.AlterField(
            model_name="apartamento",
            name="proprietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meus_apartamentos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="proprietário",
            ),
        ),
        migrations.AlterField(
            model_name="apartamento",
            name="titulo",
            field=models.CharField(
                max_length=100, verbose_name="identificador da unidade"
            ),
        ),
        migrations.AlterField(
            model_name="comodidade",
            name="nome",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="nome da comodidade"
            ),
        ),
        migrations.AlterField(
            model_name="fotoapartamento",
            name="imagem",
            field=models.ImageField(
                upload_to="apartamentos/galeria/%Y/%m/%d/", verbose_name="imagem"
            ),
        ),
        migrations.AlterField(
            model_name="predio",
            name="cep",
            field=models.CharField(max_length=9, verbose_name="CEP"),
        ),
        migrations.AlterField(
            model_name="predio",
            name="estado",
            field=models.CharField(max_length=2, verbose_name="estado (UF)"),
        ),
        migrations.AlterField(
            model_name="predio",
            name="foto_fachada",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="predios/fachadas/%Y/%m/%d/",
                verbose_name="foto da fachada",
            ),
        ),
        migrations.AlterField(
            model_name="predio",
            name="nome",
            field=models.CharField(
                max_length=255, verbose_name="nome do prédio/condomínio"
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="apartamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="apartamentos.apartamento",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="hospede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
