# Generated by Django 5.2.3 on 2025-07-09 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartamentos", "0007_alter_fotoapartamento_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.IntegerField(
                        help_text="Nota de 1 a 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comentario",
                    models.TextField(
                        blank=True,
                        help_text="Deixe seu comentário sobre a estadia.",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="apartamentos.reserva",
                    ),
                ),
            ],
        ),
    ]
