# Generated by Django 5.2.3 on 2025-07-11 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartamentos", "0008_avaliacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fotoapartamento",
            options={"ordering": ["-principal"]},
        ),
        migrations.RemoveField(
            model_name="fotoapartamento",
            name="legenda",
        ),
        migrations.AddField(
            model_name="fotoapartamento",
            name="principal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fotoapartamento",
            name="apartamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fotos",
                to="apartamentos.apartamento",
            ),
        ),
        migrations.AlterField(
            model_name="fotoapartamento",
            name="imagem",
            field=models.ImageField(upload_to="apartamentos/fotos/"),
        ),
    ]
